updated easyssh

diff --git a/easyssh b/easyssh
--- a/easyssh
+++ b/easyssh
@@ -1,8 +1,30 @@
 #!/bin/bash
 
+function fail {
+  echo $1 >&2
+  exit 1
+}
+
+function retry {
+  local n=0
+  local max=3
+  local delay=1
+  while true; do
+    "$@" && break || {
+      if [[ $n -lt $max ]]; then
+        ((n++))
+        echo "Connection failed. Attempt $n/$max:"
+        sleep $delay;
+      else
+        fail "Connection failed after $n attempts."
+      fi
+    }
+  done
+}
+
 if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
   echo "Connecting to server..."
-  ssh user@192.168.1.1 -p 22 
+  retry ssh -o ConnectTimeout=5 user@192.168.1.1 -p 22 
 else
-  echo "IPv4 is down"
+  echo "No IPv4 connection."
 fi
