add dependency check to makethumnails, and add headers

diff --git a/makethumbnails b/makethumbnails
--- a/makethumbnails
+++ b/makethumbnails
@@ -1,5 +1,41 @@
 #!/bin/bash
 
+#-------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
+#
+# Tyler(UnclassedPenguin) MakeThumbnails 2022
+#
+# Author: Tyler(UnclassedPenguin)
+#    URL: https://unclassed.ca
+# GitHub: https://github.com/UnclassedPenguin
+#
+#-------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
+
+SCRIPTNAME="${0##*/}"  
+  
+warn() {  
+    printf >&2 "$SCRIPTNAME: $*\n"  
+}  
+
+checkdeps() {
+    local -i not_found
+    for cmd; do
+        iscmd "$cmd" || {
+            warn $"$cmd is not found"
+            let not_found++
+        }
+    done
+    (( not_found == 0 )) || {
+        warn $"Install dependencies listed above to use $SCRIPTNAME"
+        exit 1
+    }
+}
+
+# If you need to check more, just add here i.e.:
+# checkdeps curl cmd cmd1 cmd2
+checkdeps mogrify
+
 mkdir thumbnails
 mogrify -verbose -path thumbnails -resize 20% ./*
 cd thumbnails
